=== DonovanPerello/TascasLlista/dades/activitats_001.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="tasques">
    <xs:complexType>
      <xs:sequence>
        
        <xs:element name="tasca" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="titol" type="xs:string"/>
              <xs:element name="descripcio" type="xs:string"/>
              <xs:element name="data" type="xs:date"/>
              
              <xs:element name="categoria">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="nom" type="xs:string"/>
                    <xs:element name="color" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

              <xs:element name="prioritat" type="xs:string"/>
              <xs:element name="realitzada" type="xs:boolean"/>
            </xs:sequence>
            
            <xs:attribute name="id" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== DonovanPerello/TascasLlista/dades/activitatXML_001.xml
<?xml version="1.0" encoding="UTF-8"?>
<tasques xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:noNamespaceSchemaLocation="activitats_001.xsd">
    <tasca id="task-001">
        <titol>Crea l'estructura de carpetes del projecte</titol>
        <descripcio>Organitza els fitxers: HTML, CSS, JS, dades...</descripcio>
        <data>2024-08-01</data>
        <categoria>
            <nom>Organització</nom>
            <color>#FF5733</color>
        </categoria>
        <prioritat>Alta</prioritat>
        <realitzada>false</realitzada>
    </tasca>
    <tasca id="task-002">
        <titol>Crear el document HTML</titol>
        <descripcio>Crear l'estructura bàsica del document HTML</descripcio>
        <data>2024-07-01</data>
        <categoria>
            <nom>Desenvolupament</nom>
            <color>#33FF57</color>
        </categoria>
        <prioritat>Alta</prioritat>
        <realitzada>false</realitzada>
    </tasca>
    <tasca id="task-003">
        <titol>Aconseguir fer el XML</titol>
        <descripcio> Conseguir fer el xml fet a ma y mostrarlo per pantalla</descripcio>
        <data>2024-09-01</data>
        <categoria>
            <nom>Desenvolupament</nom>
            <color>#33FF57</color>
        </categoria>
        <prioritat>Baixa</prioritat>
        <realitzada>false</realitzada>
    </tasca>
</tasques>
